development:
  app_id: oxvU7BRJzsuOeXusB4wnWU7t3YZrWTFxJ2N5fj9g
  master_key: lDMdjBX9er12nbFvC4oYP3ydfbFZXGw53fMdi7Yh

staging:
  app_id: oxvU7BRJzsuOeXusB4wnWU7t3YZrWTFxJ2N5fj9g
  master_key: lDMdjBX9er12nbFvC4oYP3ydfbFZXGw53fMdi7Yh

test:
  app_id: 1234567890
  master_key: abcdefgh

production:
  app_id: cnsd7iD7AKBypKtPa2VqhlLl5N7M252FFqSQOtG3
  master_key: h3Bg4yf1IpzCucHIgTcGHUXi9tDxTkgolTz78C60